name: Android Build Release CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Retrieve the secret and decode it to a file
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
      run: |
        echo "$KEY_PROPERTIES_BASE64" | base64 --decode > key.properties
        echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Stop gradle daemon
      run: ./gradlew --stop

    - name: Get Change logs
      id: get-change-logs
      run: |
        CHANGE_LOGS=`ls -r fastlane/metadata/android/en-US/changelogs | head -1`
        echo "CHANGE_LOGS=$CHANGE_LOGS" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
      
        # A file, directory or wildcard pattern that describes what to upload
        path: ./app/build/outputs/apk/release/*.apk
